/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed-dim": "#89ceff",
        "surface-dim": "#cbdbf5",
        "surface": "#f8f9ff",
        "outline": "#757684",
        "primary": "#00288e",
        "tertiary-container": "#005074",
        "on-error-container": "#93000a",
        "surface-container-high": "#dce9ff",
        "surface-bright": "#f8f9ff",
        "on-background": "#0b1c30",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#444653",
        "inverse-surface": "#213145",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#dbe1ff",
        "surface-container-low": "#eff4ff",
        "on-primary": "#ffffff",
        "inverse-primary": "#b8c4ff",
        "surface-container": "#e5eeff",
        "outline-variant": "#c4c5d5",
        "on-secondary-fixed": "#00174b",
        "primary-fixed": "#dde1ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b8c4ff",
        "on-primary-fixed": "#001453",
        "on-primary-fixed-variant": "#173bab",
        "secondary-fixed-dim": "#b4c5ff",
        "on-primary-container": "#a8b8ff",
        "on-error": "#ffffff",
        "surface-variant": "#d3e4fe",
        "tertiary": "#003853",
        "background": "#f8f9ff",
        "surface-tint": "#3755c3",
        "secondary": "#0051d5",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#003ea8",
        "secondary-container": "#316bf3",
        "primary-container": "#1e40af",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-container": "#fefcff",
        "on-tertiary-fixed-variant": "#004c6e",
        "on-surface": "#0b1c30",
        "on-tertiary-container": "#68c4ff",
        "tertiary-fixed": "#c9e6ff",
        "on-tertiary-fixed": "#001e2f"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "margin": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "margin-md": "1.5rem",
        "gutter-lg": "1.5rem",
        "margin-lg": "2rem"
      },
      "fontFamily": {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "label-lg": ["Inter"],
        "label-md": ["Inter"],
        "display": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"]
      },
      "fontSize": {
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.015em", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "label-lg": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "display": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-sm": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
